export const SECTOR_ETFS: Record<string, string> = {
  TECHNOLOGY: "XLK",
  SEMICONDUCTORS: "SMH",
  HEALTHCARE: "XLV",
  CONSUMER_STAPLES: "XLP",
  CONSUMER_DISCRETIONARY: "XLY",
  FINANCIALS: "XLF",
  INDUSTRIALS: "XLI",
  ENERGY: "XLE",
  UTILITIES: "XLU",
};
