export const STRATEGIC_THRESHOLDS = {
  ELIGIBLE_MIN_SCORE: 65,
  WATCH_MIN_SCORE: 40,
  MAX_SCORE: 100,

  RISK_GUARDRAILS_WEIGHT: 15,
  MARKET_REGIME_WEIGHT: 15,
  MACRO_ALIGNMENT_WEIGHT: 10,
  INSTITUTIONAL_SIGNALS_WEIGHT: 15,
  FUNDAMENTAL_ACCELERATION_WEIGHT: 20,
  WEEKLY_TECHNICAL_WEIGHT: 15,
  THESIS_DECAY_WEIGHT: 10,
} as const;

export const TACTICAL_THRESHOLDS = {
  TRADE_MIN_SCORE: 60,
  WATCH_MIN_SCORE: 40,
  MAX_SCORE: 100,

  TECHNICAL_ALIGNMENT_WEIGHT: 20,
  MOMENTUM_REGIME_WEIGHT: 15,
  LIQUIDITY_TRIGGERS_WEIGHT: 15,
  SENTIMENT_CONTEXT_WEIGHT: 10,
  EVENT_PROXIMITY_WEIGHT: 15,
  TIME_STOP_LOGIC_WEIGHT: 10,
  OPPORTUNITY_RANKING_WEIGHT: 15,
} as const;

export const SCORE_LEVELS = {
  HIGH: 80,
  MEDIUM: 60,
  LOW: 40,
  CRITICAL: 20,
} as const;
